import type { Users } from '../types/users.types';

class UsersService {
  async getUsers(): Promise<Users[]> {
    return [
      {
        id: '1',
        firstName: 'Brian',
        lastName: 'Maiyo',
        location: true,
        county: true,
        phoneNumber: '0712345678',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '2',
        firstName: 'Faith',
        lastName: 'Chebet',
        location: true,
        county: false,
        phoneNumber: '0723456789',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '3',
        firstName: 'Kevin',
        lastName: 'Otieno',
        location: false,
        county: true,
        phoneNumber: '0734567890',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '4',
        firstName: 'Mercy',
        lastName: 'Wanjiku',
        location: true,
        county: true,
        phoneNumber: '0745678901',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '5',
        firstName: 'Dennis',
        lastName: 'Kiptoo',
        location: false,
        county: false,
        phoneNumber: '0756789012',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '6',
        firstName: 'Sharon',
        lastName: 'Achieng',
        location: true,
        county: false,
        phoneNumber: '0767890123',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '7',
        firstName: 'Victor',
        lastName: 'Mwangi',
        location: true,
        county: true,
        phoneNumber: '0778901234',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '8',
        firstName: 'Janet',
        lastName: 'Njeri',
        location: false,
        county: true,
        phoneNumber: '0789012345',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '9',
        firstName: 'Allan',
        lastName: 'Omondi',
        location: true,
        county: false,
        phoneNumber: '0790123456',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '10',
        firstName: 'Grace',
        lastName: 'Muthoni',
        location: true,
        county: true,
        phoneNumber: '0701234567',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '11',
        firstName: 'Samuel',
        lastName: 'Kariuki',
        location: false,
        county: false,
        phoneNumber: '0711111111',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '12',
        firstName: 'Ann',
        lastName: 'Mutheu',
        location: true,
        county: true,
        phoneNumber: '0722222222',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '13',
        firstName: 'Peter',
        lastName: 'Kimani',
        location: false,
        county: true,
        phoneNumber: '0733333333',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '14',
        firstName: 'Lilian',
        lastName: 'Cherono',
        location: true,
        county: false,
        phoneNumber: '0744444444',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '15',
        firstName: 'Collins',
        lastName: 'Odhiambo',
        location: true,
        county: true,
        phoneNumber: '0755555555',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '16',
        firstName: 'Irene',
        lastName: 'Nyambura',
        location: false,
        county: false,
        phoneNumber: '0766666666',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '17',
        firstName: 'Emmanuel',
        lastName: 'Kiplagat',
        location: true,
        county: true,
        phoneNumber: '0777777777',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '18',
        firstName: 'Caroline',
        lastName: 'Atieno',
        location: true,
        county: false,
        phoneNumber: '0788888888',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '19',
        firstName: 'Joseph',
        lastName: 'Maina',
        location: false,
        county: true,
        phoneNumber: '0799999999',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '20',
        firstName: 'Mary',
        lastName: 'Wambui',
        location: true,
        county: true,
        phoneNumber: '0700000000',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];
  }
}

export const usersService = new UsersService();
